spring:
  datasource:
    url: jdbc:mysql://localhost:3306/english_news?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  resources:
    static-locations:
      - classpath:/resources
      - classpath:/static
  redis:
    database: 0
    host: 127.0.0.1
  devtools:
    add-properties: true
  mail:
    host: smtp.qq.com
    username: 863577223@qq.com
    password: pvwvnhgwuwznbfee
    port: 25
    protocol: smtp
    default-encoding: utf-8
  security:
    user:
      name: user
      password: 123456
      roles: admin
path-manager:
  security-config-path:
    login-page:
      /pages/login.html
    login-url:
      /user/login
    login-success-url:
      /home.html
    logout-success-url:
      /pages/login.html
    ant-matchers:
      - /pages/register.html
      - /pages/login.html
      - /home.html
      - /home_foot.html
      - /home_head.html
      - /jquery-3.4.1/**
      - /dist/**
      - /angular/**
      - /plugins/**
      - /user/**
  email-template-path:
    templates/emailTeplate.html